### ISSUE TITLE
DHS Add example

### ISSUE THREAD

**Issue by andreaTP** [vernamlab/cuHE#13] opened 2016-02-23 15:18 UTC
I'm trying to have an add example of DHS,
reading the Prince branch let me think that change:
https://github.com/vernamlab/cuHE/blob/master/examples/DHS/simple_DHS.cu#L25
`cAnd` in `cXor`
and 
https://github.com/vernamlab/cuHE/blob/master/examples/DHS/simple_DHS.cu#L39
`*` in `+`

should do the job, but unfortunately this doesn't work,
any hint on it?

Thanks in advance for the support!

**Comment by WeiDaiWD** [comment] 2016-02-23 16:54
1. cXor() in "CuHE.cu" did something wrong that is fixed now.
2. I put some comment in "simple_DHS_xor.cu".
   "cAnd" introduces a lot of noise. "relin" and "modswitch" are used to reduce noise.
   "cXor" is OK without "relin" or "modswitch".
3. Whenever "modswitch" is used, the ciphertext's level is increased. Hence, it should be decrypted in the increased level.

In conclusion:
cXor -> relin -> modswitch -> decrypt(1)
cXor -> decrypt(0)
are both correct!

**Comment by andreaTP** [comment] 2016-02-23 17:01
great!
Thanks for the support!

Is there any programmatic way to get control over noise level in case of multiple operations?

**Comment by WeiDaiWD** [comment] 2016-02-23 17:38
I don't think so. This noise growth is caused by the homomorphic scheme.
- Corrections:
  - "modswitch" is to slow down the noise growth, not to reduce noise. It is only needed when the circuit goes deeper. It is not necessary if there is no cAnd.
  - "relin" is to ensure correct decryption of cAnd result. Without it, decryption fails after cAnd.
- In the branch Prince and other applications I implemented (not posted yet), I did something like the following.
  Consider a single multiplicative level of the circuit as:
  **input x[m] --> one cAnd, any number of additions -->  output y[n].**
  Performing "modswitch" on all y[n].
  Perform "relin" on y[] only if it is computed from a product of x[], since "relin" is expensive.
  And decrypt with a level higher.

**Comment by WeiDaiWD** [comment] 2016-02-23 17:44
A better example: input x[4], output y=x[0]_x[1]+x[2]_x[3].
1. x[0]x[1] --> relin; x[2]x[3] --> relin; add to y --> modswitch
2. x[0]x[1]; x[2]x[3]; add to y --> relin --> modswitch
Both of them are correct. The former can be done with a programmatic method but introduces an extra relin than the latter, i.e. less efficient.

**Comment by andreaTP** [comment] 2016-03-02 11:16
I'm trying ti use `cNot` but unfortunately I always receive back a:
`Error: cNot of non-CRT domain!`

could I ask for an explanation on how to manage that?

thanks in advance!

**Comment by WeiDaiWD** [comment] 2016-03-03 17:27
cNot first checks if input is in CRT domain.
Example:
CuCtxt x; // with some initialization
x.x2c(); // convert to CRT domain
cNot(y, x); // should work fine

**Comment by andreaTP** [comment] 2016-03-04 10:45
you are right, I've provided the example that show it.
thanx!
Now I'm struggling with noise :-)

**Closed as completed** 2016-03-15 14:54 UTC
